language: node_js
node_js:
  - 12
os: osx
osx_image: xcode11.3
env:
  - SH=bash
addons:
  homebrew:
    taps: wix/brew
    packages:
      - applesimutils
      - watchman
before_install:
  - sudo gem install cocoapods
install:
  - npm install
  - npm install detox-cli
  - npm install react-native-cli
  - cd ios/ && pod install && cd ..
  - pwd
  - ls -la
script:
  - detox build -c ios.sim.release -l verbose
  - detox test -c ios.sim.release -l verbose
