language: objective-c
osx_image: xcode11.3

branches:
  only:
    - master

env:
  global:
    - NODE_VERSION=stable

install:
  - brew tap wix/brew
  - brew install applesimutils
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - nvm alias default $NODE_VERSION

  - npm i
  - npm install -g react-native-cli
  - npm install -g detox-cli
  - cd ios/ && pod install && cd ..
script:
  - detox build --configuration ios.sim.release -l fatal
  - detox test --configuration ios.sim.release --cleanup
