matrix:
  include:
    - language: android
      dist: trusty
      jdk: oraclejdk8
      env:
        global:
          - NODE_VERSION=stable
      android:
        components:
          # Uncomment the lines below if you want to
          # use the latest revision of Android SDK Tools
          # - tools
          # - platform-tools

          # The BuildTools version used by your project
          - build-tools-26.0.2

          # The SDK version used to compile your project
          - android-26
      before_script:
        - ls -la
        - pwd
        - ./travisci/android-before-scripts.sh
      before_install:
        - ./travisci/android-before-install.sh
      install:
        - ./travisci/android-install.sh
      script:
        - ./travisci/android-scripts.sh

    - language: objective-c
      os: osx
      osx_image: xcode11.3
      env:
        global:
          - NODE_VERSION=stable
      install:
        - ./travisci/ios-install.sh
      script:
        - ./travisci/ios-script.sh

