version: 2.1
jobs:
  execute-detox:
    docker:
      - image: circleci/android:api-24-node
    environment:
      JVM_OPTS: -Xmx3200m
      EMULATOR_NAME: detoxTestEmulator
      EMULATOR_OPTIONS: -no-window -noaudio -no-boot-anim
      EMULATOR_CONFIG: system-images;android-24;default;armeabi-v7a
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}
      - run:
          name: Install npm dependencies
          command: npm i
      - run:
          name: Install detox cli
          command: sudo npm install -g detox-cli
      - run:
          name: Chmod permissions
          command: cd android && sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: cd android && ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}
      - run:
          name: Setup Emulator
          command: sdkmanager "${EMULATOR_CONFIG}" && echo "no" | avdmanager create avd -n $EMULATOR_NAME -k "${EMULATOR_CONFIG}"
      - run:
          name: Build detox
          command: detox build -c android.emu.release -l verbose
      - run:
          name: Launch Emulator
          background: true
          command: |
            cd ${ANDROID_HOME}/emulator;ls
            export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
            emulator -avd $EMULATOR_NAME $EMULATOR_OPTIONS

      - run:
          name: Wait for emulator boot
          command: |
            circle-android wait-for-boot
            adb shell input keyevent 82
      - run:
          name: Test detox
          command: detox test -c android.emu.release -l verbose


  buildIos:
    macos:
      xcode: 11.3.1
    working_directory: .
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Install React Native dependencies
          command: |
            brew update
            brew install watchman
            npm install -g detox-cli
      - run:
          name: Run pod install
          command: cd ios/ && pod install
      - run:
          name: Build detox
          command: detox build -c ios.sim.release -l verbose
      - run:
          name: Test detox
          command: detox test -c ios.sim.release -l verbose




workflows:
  version: 2
  build_and_test:
    jobs:
      - buildIos
      - execute-detox
