version: 2.1
jobs:
  execute-cypress:
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
      EMULATOR_NAME: cypressTestEmulator
      EMULATOR_OPTIONS: -no-window -noaudio -no-boot-anim -no-window -accel on
      EMULATOR_CONFIG: system-images;android-29;google_apis_playstore;x86
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}
      - run:
          name: Install npm dependencies
          command: npm i
      - run:
          name: Install detox cli
          command: sudo npm install -g detox-cli
      - run:
          name: Chmod permissions
          command: cd android && sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: cd android && ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}
      - run:
          name: Setup Emulator
          command: sdkmanager "${EMULATOR_CONFIG}" && echo "no" | avdmanager create avd -n $EMULATOR_NAME -k "${EMULATOR_CONFIG}"
      - run:
          name: Launch Emulator
          command: |
            cd ${ANDROID_HOME}/emulator;ls
            export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
            emulator -avd $EMULATOR_NAME -no-window -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Wait for emulator boot
          command: |
            circle-android wait-for-boot
            adb shell input keyevent 82
      - run:
          name: Build cypress
          command: detox build -c android.emu.release -l verbose
      - run:
          name: Test cypress
          command: detox test -c android.emu.release -l verbose



workflows:
  version: 2
  build_and_test:
    jobs:
      - execute-cypress
